### PR TITLE
unfortunately i needed to rename the community-version to make the im…

### PR DESCRIPTION
**Pull request by adamstok**
Added simple tests - enjoy to modify them, create new ones, etc :+1:

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
@adamstok While I appreciate your work on this (tests are awesome), changing the file name would introduce breaking changes to this repository.
Could you make a separate version in a different file/folder? That way people can see your code, but it won't break the stuff others are already working on.

**Comment by adamstok** [comment]
> @adamstok While I appreciate your work on this (tests are awesome), changing the file name would introduce breaking changes to this repository.
> Could you make a separate version in a different file/folder? That way people can see your code, but it won't break the stuff others are already working on.

I will try my best :)

**Comment by sophiabrandt** [comment]
@adamstok While I appreciate your work on this (tests are awesome), changing the file name would introduce breaking changes to this repository.
Could you make a separate version in a different file/folder? That way people can see your code, but it won't break the stuff others are already working on.

**Comment by adamstok** [comment]
@sophiabrandt hope it's ok now ;)

**Pull request merged**
