### PR TITLE
changed the file path given in the README.md file for executing the m…

### PR DESCRIPTION
**Pull request by nikhilchintawar**
…ake_art.py file. as it is confused me because to run the file we have to give example/ztm-logo.png path and there is only ztm-logo.png and I spent 20 min on it.

### CODE REVIEW

**Comment by wmporter** [comment]
@nikhilchintawar I think the subsequent commits you made on this branch should be reverted. I would like to merge the change to the README in but the other commits are unrelated to this change.

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
This pull request has several conflicts with already existing code.
I'm on board with changing the `README.md` file, but can you please [sync your fork first](https://www.freecodecamp.org/news/how-to-sync-your-fork-with-the-original-git-repository/)?
Then we can take a better look what exactly fits with the updated code.
Also, I don't think you need to commit the `nikhil/ztm-logo.txt` file

**Comment by nikhilchintawar** [comment]
@sophiabrandt I tried to resolve the conflict and now it is showing up to date in my terminal can you please review it. and give me feedback.

**Comment by sophiabrandt** [comment]
@nikhilchintawar when I run `python3 community-version.py example/ztm-logo.png` I get 
```
Traceback (most recent call last):
  File "community-version.py", line 142, in <module>
    if sys.argv[2]:
IndexError: list index out of range
```
Can you please correct that? Or does it work for you?

**Comment by nikhilchintawar** [comment]
now I solved this issue by adding try/catch but this issue is coming because of my other PR which I have created after creating a function to save the ASCII txt file into a custom folder and filename also when i did sync my fork as you said i fetched code of other people and they also need the output folder and filename and because of that issue is coming if you want i can change the file path in README.md file or improve the code to resolve further errors. for now, it is working.

**Comment by nikhilchintawar** [comment]
also, i have a question when i resolved the conflicts of this PR then it should resolve the conflict of other PR also why it is not happening is there any reason and what I need to do resolve the conflict of that PR.

**Comment by sophiabrandt** [comment]
@nikhilchintawar I'm not really sure what's going on for you. That's hard to say without having access to your computer and really knowing what's going on step by step. I suggest you do some research on how to merge git conflicts. There are some good videos on youtube.

**Comment by nikhilchintawar** [comment]
i rsolved conflict for this PR

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Any chance you can revert the change you made you `example/make_art.py`
It would be ideal if this file could remain in tack as a starting point for other contributors

**Comment by nikhilchintawar** [comment]
@MattCSmith I am not able to revert the changes but I converted the make_art.py file into the original file. if this is not ok then what else I can do.

**Comment by MattCSmith** [comment]
Hey @nikhilchintawar 
Apologies for the delay. 
That's perfect. Unfortunately there appears to be another conflict. 
If you are able to resolve and then ping me on Discord with the link to this PR, I will merge it in asap. 

Regards

**Comment by nikhilchintawar** [comment]
@MattCSmith I resolved the conflict.

**Pull request merged**
