### PR TITLE
QT based GUI application using Tkinter

### PR DESCRIPTION
**Pull request by JudeSavio**
Just took the idea and modified into a QT GUI application that can access the file browser to get image files anywhere from the local machine and convert it into ASCII art.

The converted images are displayed within the application.

Wanted to package the app into an executable but thought that this would make up a good beginner template to play around with.

Python version used for creating the app was **python3**

Cheers!

P.S: This is my first ever pull request in a long time

### CODE REVIEW

**Review by MattCSmith — CHANGES_REQUESTED** [review]
Hey @JudeSavio 
Nice work on this, although I would really like to keep the example files in tact, so that other students can view them as a starting point. 

Any chance you could migrate your version to another file or even the community-version.py

**Comment by JudeSavio** [comment]
> Hey @JudeSavio
> Nice work on this, although I would really like to keep the example files in tact, so that other students can view them as a starting point.
> 
> Any chance you could migrate your version to another file or even the community-version.py

Hey @MattCSmith ,

This is pretty new to me, So I'm thinking of creating a new folder called 'GUI' and dumping my file there will that be fine with you?

If else can you suggest your thoughts? Thanks.

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
I can't get this to work due to missing dependencies. Can you add the dependencies to a separate `requirements.txt` file in your `GUI Version` folder or add a note which packages you need to install for this to work? (Which version of `tkinter` and peer dependencies?)

**Comment by JudeSavio** [comment]
> I can't get this to work due to missing dependencies. Can you add the dependencies to a separate `requirements.txt` file in your `GUI Version` folder or add a note which packages you need to install for this to work? (Which version of `tkinter` and peer dependencies?)

Hey @sophiabrandt , thanks for pointing out. Any python version after **3.1** will work without installing any peer dependencies or packages. But as per your request, will add add a requirements.txt file in the folder

**Note :** Any python version after 3.1 will work fine without any modifications

**Comment by JudeSavio** [comment]
@sophiabrandt , Have added a requirements.txt file as per your request.

Please do tell me, if there are any changes.

Cheers!

**Pull request merged**
