### PR TITLE
added a contours selection feature

### PR DESCRIPTION
**Pull request by AfreenInnovates**
When the contour detection option is enabled, the application utilizes the `FIND_EDGES` filter from the Pillow library to identify the edges of objects within the uploaded image. This highlights the structure and outlines, resulting in ASCII art that emphasizes shape and detail.

### CODE REVIEW

**Comment by l-white** [comment]
@AfreenInnovates Unfortunately we cannot accept this submission as it breaks the functionality of the community-version.py. Please ensure you have all the dependencies installed as outlined in the requirements.txt file and can run the project with this command: python3 community-version.py example/ztm-logo.png.

**Comment by AfreenInnovates** [comment]
how do i make sure it works?

i have downloaded the requirements.txt file

**Comment by l-white** [comment]
@AfreenInnovates First, please install the dependencies. They are listed at the top of the community-version.py file and then you can dig into them further in the requirements.txt file if necessary. It's not a matter of having the requirements file; it is there to let you know what you need to install. This file is about the dependencies you need. Next, when you run the command, you should see an output.txt file with the ASCII art. Right now with your contribution, when I run python3 community-version.py example/ztm-logo.png, I do not see the output -- I get errors around the streamlit dependency. I hope that helps.

**Comment by l-white** [comment]
@AfreenInnovates In addition, a number of lines at the end of the file were removed, which are necessary to running the application, so that's another thing to look at as well.

**Pull request merged**
