### PR TITLE
Update file-name when file uploaded

### PR DESCRIPTION
**Pull request by ndeoligence**
sub: web version

### CODE REVIEW

**Comment by peteruche21** [comment]
if the filnames can be formated with the current date-and-time, it would make the job of clean-up easier

**Comment by ndeoligence** [comment]
> if the filnames can be formated with the current date-and-time, it would make the job of clean-up easier

@peteruche21 I'm sorry, I don't understand what you mean...

**Comment by peteruche21** [comment]
Oh
What i meant is that, in production we will work with databases and having a filename with date format can aide us navigate the file lookups insertion and deletions

**Comment by ndeoligence** [comment]
That's not the scope of this PR though. I'm just making sure that the component that always says "No file selected" updates when a file's been uploaded.

Maybe you should create a new issue for the feature you want?

**Pull request merged**
