### PR TITLE
Branchtoaddluconttf

### PR DESCRIPTION
**Pull request by singhana7272**

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
```bash
Enter the image path : lena.jpg
Traceback (most recent call last):
  File "asciiart.py", line 20, in <module>
    font = ImageFont.truetype('C:\\Windows\\Fonts\\lucon.ttf',15)
  File "/home/user/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/home/user/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/user/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```
Still errors. Can't you try to use a different font that's available on every system and load it differently?
This seems to rely on the Windows font cache?

**Comment by singhana7272** [comment]
I have updated the code please take a look again.

**Comment by singhana7272** [comment]
@sophiabrandt have u tried to run the code ?

**Comment by sophiabrandt** [comment]
@singhana7272 
```python
Enter the image path : lena.jpg
Traceback (most recent call last):
  File "asciiart.py", line 37, in <module>
    font=font,fill = (r,g,b))
NameError: name 'font' is not defined
```

**Comment by MattCSmith** [comment]
Closing this PR due to the age feel free to resolve and reopen 🙂

**Pull request closed without merging**
