### PR TITLE
added colored ascii converter folder

### PR DESCRIPTION
**Pull request by singhana7272**

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Error:
```python
File "asciiart.py", line 20, in <module>
    font = ImageFont.truetype('C:\\Windows\\Fonts\\lucon.ttf',15)
  File "/home/owlhoot/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/home/owlhoot/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/user/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

There seem to be some dependencies that are installed on your system that are not univeral, see `C:\\Windows\\Fonts\\lucon.ttf`.
I'm not a Windows user, so your library breaks. Can you find a way to provide all required dependencies, please?

**Comment by singhana7272** [comment]
> Error:
> 
> ```python
> File "asciiart.py", line 20, in <module>
>     font = ImageFont.truetype('C:\\Windows\\Fonts\\lucon.ttf',15)
>   File "/home/owlhoot/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
>     return freetype(font)
>   File "/home/owlhoot/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
>     return FreeTypeFont(font, size, index, encoding, layout_engine)
>   File "/home/user/.virtualenvs/ascii-art/lib/python3.8/site-packages/PIL/ImageFont.py", line 193, in __init__
>     self.font = core.getfont(
> OSError: cannot open resource
> ```
> 
> There seem to be some dependencies that are installed on your system that are not univeral, see `C:\\Windows\\Fonts\\lucon.ttf`.
> I'm not a Windows user, so your library breaks. Can you find a way to provide all required dependencies, please?
I have added lucon.ttf to folder colored ascii converter in my PR #32 .

**Comment by singhana7272** [comment]
I have added lucon.ttf to folder colored ascii converter in my PR #32

**Comment by sophiabrandt** [comment]
Duplicate of #32. Please add corrections to one pull request. When they are merged, they would overwrite each other otherwise.

**Comment by singhana7272** [comment]
Ohh sorry, i don't know that how to do corrections in same pull request
that's why I have created a new PR #32.

Have you tried.. I have added lucon.ttf is it working now?

**Pull request closed without merging**
