### PR TITLE
refactor pyjoke addition

### PR DESCRIPTION
**Pull request by BarakStout**
The implementation did not have the `pyjoke` module in a function. The code was fetching a random joke and assigning it to an unused variable randomly in the code. This PR will have the `pyjoke` module as a function that can be called as needed.

### CODE REVIEW

**Comment by Somil-Tyagi** [comment]
Its corrected by me already in my pr

**Comment by BarakStout** [comment]
@Somil-Tyagi it looks like you added it to the `show_credits()` function. Mine has it as a separate function. Not quite the same thing.

**Comment by Somil-Tyagi** [comment]
> @Somil-Tyagi it looks like you added it to the `show_credits()` function. Mine has it as a separate function. Not quite the same thing.

so whats the difference it does the same thing, positioning not matter, and you can not make pull request just by changing its position try making some actual changes in the program then you can say to yourself " YES I'VE DONE SOME CONTRIBUTION IN THIS PROJECT"

**Comment by BarakStout** [comment]
@Somil-Tyagi it's refactoring code, not adding anything new or removing anything. Just a little better.

**Comment by sophiabrandt** [comment]
I've marked this invalid for hacktoberfest, as this PR only seemed to add errors?

**Comment by BarakStout** [comment]
> I've marked this invalid for hacktoberfest, as this PR only seemed to add errors?

What errors did it add?

**Pull request merged**
