### PR TITLE
UPDATED README.md

### PR DESCRIPTION
**Pull request by singhana7272**

### CODE REVIEW

**Comment by abdus** [comment]
#21

**Comment by singhana7272** [comment]
Why it is counted as invalid?

**Comment by singhana7272** [comment]
Sir, why do you labelled my PR as conflict present. As I did updated
README.md file.

Please tell me reason.

**Comment by abdus** [comment]
> Why it is counted as invalid?
you could have added changes this PR proposes into #21. may I ask why two separate PR for such small changes?

**Comment by singhana7272** [comment]
Sir i am very new to this, i have just learnt about git and github. I am
really sorry for that.

I will combine my PRs for these small changes.

**Comment by abdus** [comment]
Alright, That's great! 
(this PR shall remain invalid btw)

**Pull request closed without merging**
