### PR TITLE
Separate CLI logic from util functions

### PR DESCRIPTION
**Pull request by ndeoligence**
add requirements file

### CODE REVIEW

**Comment by ndeoligence** [comment]
Resolved merge conflicts

**Comment by sophiabrandt** [comment]
@ndeoligence any way you could try to merge the conflicts again? I tried doing that, but as I'm not as familiar with your changes as you are, I am not sure where changes are exactly needed. Thank you.

**Comment by ndeoligence** [comment]
@sophiabrandt sure, I'll do it in a couple hours... Thanks for the reply

**Comment by ndeoligence** [comment]
@sophiabrandt Done

**Comment by ndeoligence** [comment]
@sophiabrandt Done

**Pull request merged**
