### PR TITLE
adding rotating functionality in image

### PR DESCRIPTION
**Pull request by jolanipekun**
Please have a look at this functionality and comment how I can improve it. @kennithnichol

### CODE REVIEW

**Comment by monde16** [comment]
Thanks again @jolanipekun for your PR.
I notice you made changes to `make_art_python2.py` instead of `ascii_art.py`.
Please have a read through the project [Readme](https://github.com/zero-to-mastery/ascii-art#how-to-contribute) file - under **How to contribute.**

If/when you implement the code in that file, then please help make it reusable by making the following changes:
1. Your code currently only rotates the same image every time. And it'll make the code fail when someone doesn't have the file you're trying to open. So maybe refactor your implementation into a method.
2. Instead of opening an image in your code, you can work with an image object (and assume the caller will have created the object).
3. Instead of hard-coding the angle of rotation, maybe add it as a parameter - and specify the unit (deg/rad) in the docs.
4. And finally, if you make a method, you don't have to worry about showing the image. The caller will do with it whatever they want - like writing it to a file (as a rotated ascii). If you make it into a method, we can help you with how to hook it into the existing code as an option. Here's an example of a function that just needs your implementation:
```python
def rotate_image(image, angle):
    """
    Rotates an image by the given angle (degrees) and returns it.
    """
    # Image rotation implementation goes here...
    return image
```
* If you're eager to try this out, you can check out the `scale_image` function in `ascii_art.py` (I think it's very similar in style to what you're doing. If you run `ascii_art convert --help` (Again, see Readme: How to contribute) you should see it mentioned as an option (-w OR --width). And if you look at `cli.py` you should be able to follow how the `-w` option gets to the **scale_image** function being called.
* Last tip is, if you wanna try adding the option, note that `-r` is already used (how about `-a` for angle?). And you'll wanna apply the rotation either before/after scaling is done. Actually, anytime before the image is converted to ascii.

Sorry for the long list, but I hope it helps.

**Comment by ndeoligence** [comment]
Thanks again @jolanipekun for your PR.
I notice you made changes to `make_art_python2.py` instead of `ascii_art.py`.
Please have a read through the project [Readme](https://github.com/zero-to-mastery/ascii-art#how-to-contribute) file - under **How to contribute.**

If/when you implement the code in that file, then please help make it reusable by making the following changes:
1. Your code currently only rotates the same image every time. And it'll make the code fail when someone doesn't have the file you're trying to open. So maybe refactor your implementation into a method.
2. Instead of opening an image in your code, you can work with an image object (and assume the caller will have created the object).
3. Instead of hard-coding the angle of rotation, maybe add it as a parameter - and specify the unit (deg/rad) in the docs.
4. And finally, if you make a method, you don't have to worry about showing the image. The caller will do with it whatever they want - like writing it to a file (as a rotated ascii). If you make it into a method, we can help you with how to hook it into the existing code as an option. Here's an example of a function that just needs your implementation:
```python
def rotate_image(image, angle):
    """
    Rotates an image by the given angle (degrees) and returns it.
    """
    # Image rotation implementation goes here...
    return image
```
* If you're eager to try this out, you can check out the `scale_image` function in `ascii_art.py` (I think it's very similar in style to what you're doing. If you run `ascii_art convert --help` (Again, see Readme: How to contribute) you should see it mentioned as an option (-w OR --width). And if you look at `cli.py` you should be able to follow how the `-w` option gets to the **scale_image** function being called.
* Last tip is, if you wanna try adding the option, note that `-r` is already used (how about `-a` for angle?). And you'll wanna apply the rotation either before/after scaling is done. Actually, anytime before the image is converted to ascii.

Sorry for the long list, but I hope it helps.

**Comment by kennithnichol** [comment]
@jolanipekun did you want to follow up the comments by @ndeoligence ?

**Comment by MattCSmith** [comment]
Closing due to age

**Pull request closed without merging**
