### PR TITLE
added the feature of animating the ASCII art and download the animated art as a GIF

### PR DESCRIPTION
**Pull request by shashankjangde**
# **Enhancement: Animated ASCII Art Feature**

This update introduces a new feature that animates ASCII art and displays it as a GIF. A sample of the animated art can be found in the temp directory and is linked below for your reference.

Animated ASCII Art Sample

## **Updated Sidebar Settings:**

Sidebar Settings Update

### **Key Modifications:**

- **Animated ASCII Art Functionality:** Implemented the ability to create animated ASCII art.
- **Animation Speed Control:** Added a duration slider to adjust the animation speed of the GIF.
- **GIF Download Capability:** Updated the code to enable downloading of the GIF.
- **Temporary Files Management:** Removed temporary files generated during the GIF creation process, ensuring only the final GIF is stored in the temp directory.
- **Image Resizing:** Enhanced the functionality to adjust the width of the image while preserving its original aspect ratio.

### **Compatibility Updates:**

- **Aspect Ratio Preservation:** Introduced a new function to maintain the aspect ratio during resizing, which is now utilized in the animation process.
- **Color Theme Compatibility:** Ensured compatibility with various color themes and patterns (excluding emojis, which have their own color settings):

  ## **Neon Theme:**
  Neon Theme

  ## **Pastel Theme:**
  Pastel Theme

  ## **Grayscale Theme:**
  Grayscale Theme

- **CLI Compatibility:** Updated the CLI image conversion code block to work seamlessly with the new functionality.

### **Note:** 
This feature is only available when colorized ASCII art is enabled.

@szabopeter @kennithnichol @beneyal @Nitsujcm @wmporter

### CODE REVIEW

**Comment by l-white** [comment]
@shashankjangde Please resolve your merge conflicts and we will take a look.

**Comment by shashankjangde** [comment]
> @shashankjangde Please resolve your merge conflicts and we will take a look.

@l-white I'm sorry for the late reply. I'll look into it right away and would try to resolve the merge conflict asap.

**Comment by l-white** [comment]
@shashankjangde Another thing you can try is to create your work in a separate file that we can run with python3. That way you're not trying to keep up with the community.py file.

**Comment by shashankjangde** [comment]
> @shashankjangde Another thing you can try is to create your work in a separate file that we can run with python3. That way you're not trying to keep up with the community.py file.

@l-white Yes mam, in the beginning I was thinking of doing that but somewhere in the instructions I read that all the contributions should be made in the community-version.py and thus I decided to go ahead and contribute to community version.

And I have made all the necessary changes over the latest commit of master.
please refer to this PR: https://github.com/zero-to-mastery/ascii-art/pull/256

**Pull request closed without merging**
