### PR TITLE
Made client folder with React and setup styling guides with eslint

### PR DESCRIPTION
**Pull request by milan090**
Made client folder with React and setup styling guides with eslint and prettier formatting. #1

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Can you please elaborate on the use case? This seems to add `create-react-app`, but it doesn't connect the Python code to the front-end.

**Comment by sophiabrandt** [comment]
I've converted this to a draft/work-in-progress.

**Comment by milan090** [comment]
Ok, the backend is also being done. Will work on connecting as soon as it's done.

**Comment by MattCSmith** [comment]
Closing due to age, feel free to repopen if required

**Pull request closed without merging**
